keys: 
  - &admin_wilkuu age1hsxrd9shau86k7zz9wfdeplldyg5c2al6umnr7rn6tf7ewus64uswufr0a
  - &server_apocalypse age19cw4x4ycrdhfdkwvp009czmvfhucpdtn8lme4ja0rvq7er87z3wsd2fxz7 
  - &server_omega_relay age1n20lpr5x2aep3l3ta62x2c9cnuz3m495f2dmguqs08ezlqgu4vwsqfskyg
  - &vm_omega_relay age13x9grwfpqjgvjfcnwg5snuntp5emze85hqc8qwuz9nfphfe2pg4skl29r4 

creation_rules: 
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    age: 
      - *admin_wilkuu
      - *server_apocalypse 
  - path_regex: secrets/apocalypse/[^/]+\.(yaml|json|env|ini)$
    age: 
      - *admin_wilkuu
      - *server_apocalypse 
  - path_regex: secrets/omega-relay/[^/]+\.(yaml|json|env|ini)$
    age: 
      - *admin_wilkuu
      - *server_omega_relay 
      - *vm_omega_relay 

