prometheus:
    stalwart-pass: ENC[AES256_GCM,data:hZJXAnjoUzMyMM9KUcg8pFGJQO3VT4Unz5c51Osu47Q=,iv:HacjhSg+c6Eia7X3k6JtKbyiUFGB0Leea1wamjGBEFM=,tag:QIz/uncRORzojlEehnxyJQ==,type:str]
    mikrotik:
        username: ENC[AES256_GCM,data:bC7SChQg6xi1Sw==,iv:4hMXhV1le5Jxvmatc6Rw0RZTj6/HNKtJ1E8CUExpY1Y=,tag:LImUR9ApbWJqd0DN67L0Xg==,type:str]
        password: ENC[AES256_GCM,data:FI0DZAEwK/PU+FqGvn44GofMCeMhiPyt2gNHr0HFOoJt,iv:QrCs2hK+rxi9E1DoZQPmTDnXBGoZnlxRZXt0a8rGguk=,tag:JioHPEX/MIa/gkSmKD3RmQ==,type:str]
grafana:
    secret: ENC[AES256_GCM,data:FVMjDWPusLf0P1oqnHFZBIl39dwY+rXgQHl0kaeyQwFnI2t2SAUuDy6mbWPXE4tbZj6EJ2NeenvAXCfAb6KbrQ==,iv:+D5MBCrLmsgV54ptB8xM+1GR87HgDwnSBZV8U0EDQDU=,tag:g37+3XKf0djIaEGxe/jdeA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5U09oaUlseWJyUkM1WWcy
            a1Z5c0I0YXVuejdoKy9GaHlUMnZ5eTVaVGxvCmo0TjZ2d2RSMkRCZzU5bFgrVEJR
            UjI1OEtsRUpXUGtwVlh5RzArZy8yMlEKLS0tIGp4Q1V4N3pMMnljYkJ4WjdvODdX
            azV1a2lFUW1Ic2VacktoZkdjK3M5Y1UKfSob+dIKNmb4XjZt4wyEDhq6/AC/1X2m
            +LUun1SFiLOQzlAzM9IczrobHe+ThlffObl8ESq6pKwpBC2fP2QIPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hsxrd9shau86k7zz9wfdeplldyg5c2al6umnr7rn6tf7ewus64uswufr0a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdVFkbHdtVDRnN2o2d09B
            WExJNGhMTk9zVEFURW5MckF3V01lMTJ6azNBCldDektkWms5aHU1TTV0RDZhUjZG
            NHhpWUJHRG9nV29rV1FKZFRuME1lMHMKLS0tIHhwQ0d5YlhrdW5mUkxGT0NjS3hR
            VGdYeFc2QWNic2RuQ05KRnhkUmZUYlEKXUA4WE/+5gKZ774P+n2phQfnulXBPCek
            ZrGi8v9dUJAJpv0mTzksNCotiMrMi9R3RS1J1k24a97FTyNNG10WOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yd07835r408vk259jk09wa0seg5ymu97mh556wgu0twf35588cms7y9jht
    lastmodified: "2026-06-22T14:52:00Z"
    mac: ENC[AES256_GCM,data:p/uvg7wUDHhiXHgxiN0e/2F4urxqO+gI40Vy8AMu78GhkSheZymokmQMBO5QsNyP3kjnbOQfQoqaBaMOBIEzU+FQagbtAnZvrVCmzwZ6BcPVjC0BLBCQFtpbXigXbAuGJArez2LuJM76u3YreOdp/zxTvQVN4t6iFI+LmXjRP6U=,iv:53BCVeGW5zMPpGv+diufmhzbF6b+89RcWK419z2mPPM=,tag:9ecyz00IaPccGP6XN0X/bQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
